### ISSUE TITLE
Possible improvement for the French translation

### ISSUE THREAD

**Issue by Massedil** [martykan/forecastie#214] opened 2017-07-03 17:33 UTC
On the widget translated in French : 
1. In French, there is an unbreakable space before the char ":"
  a. Pression: --> Pression :
  b. Humidité: --> Humidité :
  c. ...
2. There is a remaining "\n" which is not interpreted and displayed before "Dernière mise à jour".

**Comment by Massedil** [comment] 2017-07-03 17:34
![screenshot_20170626-011445](https://user-images.githubusercontent.com/20357783/27802838-7f1cdb6e-6026-11e7-8db1-7ed07ecc6218.png)

**Comment by robinpaulson** [comment] 2017-07-04 04:15
I believe #211 fixes this, it will be released in 3 weeks

**Comment by Massedil** [comment] 2017-07-04 15:29
I think #211 will only fixes the point n°2. Thanks ! :)

But #211 will not add an unbreakable space before a colon, isn't it ?

**Comment by robinpaulson** [comment] 2017-07-05 02:21
I'm not sure. Are you suggesting there should be a "\\n" on line 20 also (before the "\%s")?

**Comment by Massedil** [comment] 2017-07-05 08:08
> Are you suggesting there should be a "\n" on line 20 also (before the "%s")?

No !

I suggest to put a space (punctuation) before each colon ":" because in France there is a space before a colon.

For example, the correct punctuation is "Lever du soleil : 05:36" and not "Lever du soleil: 05:36".

**Comment by robinpaulson** [comment] 2017-07-06 00:11
OK, got it. Do you want to prepare a pull request?

**Comment by robinpaulson** [comment] 2017-07-06 00:13
Or list the files and lines where we should make the changes?

**Comment by robinpaulson** [comment] 2017-07-07 07:28
OK, looking at the file listed above, in strings.xml, I think there are two lines with the error you mention, number 19 and 20. I'll adjust those two by adding an extra space, then close this issue.

**Comment by Massedil** [comment] 2017-07-07 12:52
Sorry for the delay.

> I think there are two lines with the error you mention, number 19 and 20. I'll adjust those two by adding an extra space, then close this issue.

Yes, here the space is missing.

But, there is other parts where the space is missing, you can look at this screenshot :

![27802838-7f1cdb6e-6026-11e7-8db1-7ed07ecc6218](https://user-images.githubusercontent.com/20357783/27958334-d925ef34-6322-11e7-996a-a5499f650e57.png)

But may be this cannot be corrected in the file "values-fr/strings.xml".

**Comment by robinpaulson** [comment] 2017-07-07 12:59
Right, I see. We *could* add trailing spaces in the strings-fr.xml files, after each word. That sounds clumsy though, I'm wary of doing that without thinking carefully about it first.

**Comment by Massedil** [comment] 2017-07-07 13:11
Personally, I think it's not very clean to add a space after each word in strings-fr.xml. I don't know how the other projects solve this problem. 

However, in my opinion, it's not a blocking problem to leave forecatie as it is.

**Comment by robinpaulson** [comment] 2017-07-07 13:14
No, it's not clean, but what parts of human language and culture are? ;-)

I agree, not blocking, but if we can fix it we should. I'm tempted to go with the trailing spaces, but should find out what else in the app it will affect. That is fiddly and will take time,

**Comment by robinpaulson** [comment] 2017-07-12 02:43
v1.5 is out, it will fix a small number of the problems. Moving this bug to milestone v1.6

**Comment by robinpaulson** [comment] 2019-10-17 10:50
@Massedil Have you thought any more about this, what we might do?

**Comment by Massedil** [comment] 2019-10-17 13:30
> Have you thought any more about this, what we might do?

No. I don't know what is the best way to correct this translation problem.

May be the easiest way is to put a non-breaking space [here](https://github.com/martykan/forecastie/blob/master/app/src/main/res/values-fr/strings.xml) : 

```
<string name="wind">Vent </string>
<string name="pressure">Pression </string>
<string name="humidity">Humidité </string>
<string name="sunrise">Lever du soleil </string>
<string name="sunset">Coucher du soleil </string>
```

As you said before...

> Right, I see. We could add trailing spaces in the strings-fr.xml files, after each word. That sounds clumsy though, I'm wary of doing that without thinking carefully about it first.

**Comment by robinpaulson** [comment] 2019-10-17 13:50
Shall we try it? The absolute worst thing that could happen is the entire app is broken and we release a revert for the next version 3 days later. More likely (but I still think not that likely) is the French translation is broken, in which case we revert that. Either way, nothing terrible.

**Comment by Massedil** [comment] 2019-10-17 16:24
Can't you try and build locally an apk and test ?

If you give me an apk, I can install it and test it before you commit the modification on github.

**Comment by robinpaulson** [comment] 2019-10-17 22:31
I could, I guess I'm thinking what will happen with other languages. I think it'll be fine, it's just another character. Do you want to submit a pull request or shall I do it?

**Comment by robinpaulson** [comment] 2019-10-17 23:05
I think I'm worrying too much/freewheeling on what *might* happen, rather than what will happen.

**Comment by Massedil** [comment] 2019-10-18 08:42
> Do you want to submit a pull request or shall I do it?

Sorry, I don't have the dev environment to submit a pull request and I don't really know how is organized the source code of this project. 

So you can do it, I can test an apk before you release the modification.

**Comment by robinpaulson** [comment] 2019-11-13 08:46
I added the spaces, I'll make a new release in a week or so. Let me know how it looks to you, or if I've missed any.

**Comment by robinpaulson** [comment] 2019-11-13 08:48
By the way, I noticed in this comment https://github.com/martykan/forecastie/issues/214#issuecomment-313672709 there is a problem in the final line of the text in the screenshot. Is that how it appears on your device?

**Comment by Massedil** [comment] 2019-11-13 09:31
> I added the spaces, I'll make a new release in a week or so. Let me know how it looks to you, or if I've missed any.

Thanks, I'll let you know next release !

> By the way, I noticed in this comment #214 (comment) there is a problem in the final line of the text in the screenshot. Is that how it appears on your device?

You corrected this "final line" problem here : 
https://github.com/martykan/forecastie/issues/214#issuecomment-312776534
https://github.com/martykan/forecastie/pull/211/files

So now the final line is correctly displayed for me now !

**Comment by robinpaulson** [comment] 2019-11-14 01:41
I'll close this for now then, please let us know if the issue is not fixed. And sorry for taking so long, I should have done this earlier.

**Closed by robinpaulson** 2019-11-14 01:41 UTC
Labels: bug, translation
