### ISSUE TITLE
Unset Default temperature unit

### ISSUE THREAD

**Issue by ThePreviousOne** [martykan/forecastie#206] opened 2017-06-25 04:57 UTC
![screenshot_20170624-101252](https://user-images.githubusercontent.com/13936351/27513769-45c97e4e-5941-11e7-80b4-cbf0ab80a8f3.png)
![screenshot_20170624-101625](https://user-images.githubusercontent.com/13936351/27513770-4745db28-5941-11e7-93a4-2d468c62f82a.png)
![screenshot_20170624-155437](https://user-images.githubusercontent.com/13936351/27513772-4895ab16-5941-11e7-8bee-4e31edf8e152.png)

**Comment by ildar** [comment] 2017-06-25 05:26
You seem to have temperature in Kelvin. Is that what you intended?

**Comment by ThePreviousOne** [comment] 2017-06-25 05:33
No, actually it was unset....? Just checked.  297 K is cold isn't it?
BTW v1.4

**Comment by ildar** [comment] 2017-06-25 05:36
No, it's 24 of Celsius

**Comment by ThePreviousOne** [comment] 2017-06-25 05:37
ya that setting the value fixed it

**Comment by ThePreviousOne** [comment] 2017-06-25 05:39
Unrelated did you just know that conversion or was some calculator involved ... I'm impressed

**Comment by ildar** [comment] 2017-06-25 06:13
That's in school program of physics 😉

**Comment by robinpaulson** [comment] 2017-06-26 01:41
Appears resolved, closing

**Comment by robinpaulson** [comment] 2017-06-29 09:31
As @brarcher points out, this is not actually resolved.

Suggestions what to do?

**Comment by DerVerruckteFuchs** [comment] 2017-07-05 23:11
I'm getting a similar issue with the default temperature being measured in Kelvin, but I'm getting "F" for my unit. Normally Fahrenheit is "°F". Is the unit being set based on locale or location? The alpha/char portion of the unit seems to be set to a decent default, save for the missing "°". It seems that whatever detection is being used to determine a default unit is not quite complete. Assuming that's intended behavior.

**Comment by DerVerruckteFuchs** [comment] 2017-07-05 23:19
Alright, so I cleared my app cache/config for Forcastie, force stopped it, and switched my system language to "English (United Kingdom)" from "English (United States)". Upon restarting the app I got my default location as "London, GB" with "C" as my units. Temperature is still in Kelvin. It seems part of the defaults are locale/system language based.

**Comment by robinpaulson** [comment] 2017-07-06 00:15
@DerVerruckteFuchs I'm not sure how units are selected, I assumed it was by the user, ignoring locale

**Comment by robinpaulson** [comment] 2017-07-06 01:27
This code:
https://github.com/martykan/forecastie/blob/master/app/src/main/java/cz/martykan/forecastie/utils/UnitConvertor.java

show no indication that temperature units are selected by locale.

**Comment by robinpaulson** [comment] 2017-07-06 01:41
martykan made some changes yesterday, they may have fixed the problem.
https://github.com/martykan/forecastie/commit/6870c154a7d7958d91ae747e723a2ae955e49696
#6870c15

**Comment by robinpaulson** [comment] 2017-07-07 08:50
Closing, this will appear in v1.5 in a few days

**Closed by robinpaulson** 2017-07-07 08:50 UTC
Labels: bug
