### ISSUE TITLE
Some text has not been translated into Chinese

### ISSUE THREAD

**Issue by sjl872964789** [martykan/forecastie#504] opened 2020-08-23 06:20 UTC
**Describe the bug**
Some text on the page has not been translated (Chinese)

**Context**
 - Device: [MI CC 9e]/[PIXEL XL]
 - OS version: [MIUI 10.2.10]/[Android 10.0]
 - App version: [1.10.2]

**Expected behavior**
The text is translated correctly

**Screenshots**
screen1:
<img src="https://user-images.githubusercontent.com/15941953/90972444-a7dfee80-e54b-11ea-8909-701e0d80cedb.png" width="300" height="600"/>

screen2:
<img src="https://user-images.githubusercontent.com/15941953/90972445-aadadf00-e54b-11ea-87c7-49aac3382045.png" width="300" height="600"/>

screen3:
<img src="https://user-images.githubusercontent.com/15941953/90972456-bcbc8200-e54b-11ea-888c-a3b1a17c10ec.png" width="300" height="600"/>

screen4:
<img src="https://user-images.githubusercontent.com/15941953/90972460-bfb77280-e54b-11ea-967a-e7fb0e1ae628.png" width="300" height="600"/>

**Comment by robinpaulson** [comment] 2020-09-07 08:36
> Locations -> 位置
> provide the custom simpledateformat string to be used -> 提供要使用的简单自定义日期格式的字符串
> Wind Speed ->风速
> UV Index: Low/Moderate/High/very high/Extreme -> 紫外线指数：低/中等/高/很高/极高

I've added three of these strings, the other ("Locations") is a deeper bug than i realised and will take a few more days to fix.

**Comment by robinpaulson** [comment] 2020-09-07 16:27
OK, done. The new release will be out on f-droid in a couple of days, or check the releases page for an arm binary available now. Closing, but please add comments if more translations are required.

**Closed by robinpaulson** 2020-09-07 16:27 UTC
Labels: bug, complexity: LOW, translation, urgency: MEDIUM

**Comment by robinpaulson** [comment] 2020-09-12 10:59
@sjl872964789 Did you get a chance to try the new version yet, could you let me know if the problem is fixed?

**Comment by robinpaulson** [comment] 2020-09-12 11:40
"Make widget transparent" appears to be missing too, from your screenshot

**Comment by sjl872964789** [comment] 2021-01-16 09:20
Hi, I just tried the latest version, it seems that the problem has been solved
