### ISSUE TITLE
Bug: Locations services off gets london weather

### ISSUE THREAD

**Issue by trymeouteh** [martykan/forecastie#340] opened 2019-04-02 05:13 UTC
I have the Update Location In Background checked off in the settings and everytime it does an update interval when my location services ia turnes off it gets the weather for london. I think it should just get the weather for the last known location or the last viewed city you searched in the app

**Comment by zeugmatis** [comment] 2019-04-05 22:08
Looks like this is a dupe of open bug #325 - @trymeouteh maybe try looking and adding comments there.

**Closed** 2019-04-05 22:41 UTC
