### ISSUE TITLE
Malformed query in City Search causes silent failure

### ISSUE THREAD

**Issue by n-xlkt** [martykan/forecastie#460] opened 2020-04-05 16:06 UTC
***Scenario:*** As a user, I want to understand why my location search failed, so that I can avoid issues in the future.

_Given_  I tap the <magnifying glass icon> search button,
- _And_  type in a location separated by a comma,

_When_  I click the "OK" button,
- _And_ my query cannot be processed successfully,

_Then_  I am told how to properly format my query,
- _And_ the process **does not** fail silently.

**Comment by robinpaulson** [comment] 2020-04-06 07:29
I think this is part of #316 . I'll leave it open for now though, it's not a dupe.

**Comment by robinpaulson** [comment] 2020-04-06 08:10
FYI, there is also this issue, which is on a related topic: #420

**Comment by robinpaulson** [comment] 2020-04-12 01:35
Another reason for using an OWM library #438

**Comment by lmaths** [comment] 2020-04-15 11:56
Hi guys, and if instead of informing the user how to search, why not treat the error? for example, we can remove special characters and apply a pattern.

**Comment by robinpaulson** [comment] 2020-04-16 01:25
Yes, this is a good suggestion for some classes of errors. However, we also need to account for well-formed but non-existent places.

**Comment by robinpaulson** [comment] 2020-04-16 02:39
So for instance I live in Auckland, NZ. If I were to type "Ayckland, NZ", I'd expect an error message of something like:

"This place does not exist, does it exist and is it spelled correctly?"

or:

"This place does not exist, did you mean [list of possible matches]?"

I'm not keen in invisibly fixing the name and not notifying the user, we must let them know what the problem is (as the original user pointed out) and if possible, what the potential fixes are.

**Comment by FridoDeluxe** [comment] 2020-05-13 19:49
This issue is similar to #324.

**Comment by FridoDeluxe** [comment] 2020-05-30 18:27
If I'm not missing anything so far the city search process does not fail silently. But in case no city was found only a generic _"Error parsing JSON."_ was shown which is not helpful.

Until now the code expected an 404 code for not-found cities while currently the OWM **find API** behaves differently and sends a successful but empty response. I adjusted the code, now the count of results leads to the correct error message, see #479.

Of course an additional hint how to format the city search string might be helpful. This could always be displayed above the search box.

**Comment by robinpaulson** [comment] 2020-08-01 12:56
I'm going to close this for now, the original bug has been fixed by recent updates.

**Closed** 2020-09-17 08:55 UTC
Labels: bug, complexity: MEDIUM, urgency: MEDIUM

**Comment by Lee-Carre** [comment] 2022-03-15 03:51
> silent failure

* Eric Raymond's [The Art of Unix Programming § Rule of Repair: Repair what you can — but when you must fail, **fail noisily and as soon as possible**](http://www.catb.org/esr/writings/taoup/html/ch01s06.html#id2878538)
* [give early feedback if something does not work](//www.martinfowler.com/ieeeSoftware/failFast.pdf)

---

Re city matching:

I recently learned (via a mail exchange with staff) that OWM uses [GeoNames](//www.geonames.org/) ([map](//www.geonames.org/v3/)) for locations.

So, it would seem sensible to first ensure that the desired cities have the proper names & metadata in the GeoNames data.
