### ISSUE TITLE
Crash with widget

### ISSUE THREAD

**Issue by ChefKeeper** [martykan/forecastie#327] opened 2019-02-20 11:11 UTC
When I start Forecastie from widget I got crash. Here is the log : 
`02-19 18:38:31.867 19871 19871 E AndroidRuntime: FATAL EXCEPTION: main 02-19 18:38:31.867 19871 19871 E AndroidRuntime: Process: cz.martykan.forecastie, PID: 19871 02-19 18:38:31.867 19871 19871 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.martykan.forecastie/cz.martykan.forecastie.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.app.ActivityThread.-wrap11(Unknown Source:0) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.os.Looper.loop(Looper.java:164) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6494) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at java.lang.Float.parseFloat(Float.java:452) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:467) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:216) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.app.Activity.performStart(Activity.java:7029) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741) 02-19 18:38:31.867 19871 19871 E AndroidRuntime: ... 9 more`

**Comment by robinpaulson** [comment] 2019-02-26 00:07
Is this repeatable, or a one-off?

**Comment by ChefKeeper** [comment] 2019-02-26 09:21
It is repeatable when I haven't started the app for a longer period (2-3 hours ?) it does the crash. However strangely enough when I manually close it, and even force close it in android settings it doesn't happen. Please let me know if there is any way I can help you.

**Comment by mkulesh** [comment] 2019-03-04 21:59
Hi @robinpaulson, I have the same crash:
`
    --------- beginning of crash
2019-03-04 22:45:56.706 6357-6357/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cz.martykan.forecastie, PID: 6357
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:464)
        at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:213)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2952)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
`
I have Android 9 (Nokia 8). The app has permission for working in background, battery saving mode is disabled for the app. The problem is repeatable. HTR:
- Ensure that widget shows a valid region (in my case, Bremen, DE)
![initial](https://user-images.githubusercontent.com/30557348/53765598-c3c38080-3ed0-11e9-9193-82f8c6ad10f8.png)
- Switch off the screen and wait about 20-30 minutes
- Switch off the screen and ensure that widget shows region London, DB instead of initial valid region
- Touch the widget
*BAD*: application crashes
*DESIRED*:  application starts without crash

**Comment by dawidd6** [comment] 2019-03-14 22:32
```
FATAL EXCEPTION: main
Process: cz.martykan.forecastie, PID: 21731
java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.martykan.forecastie/cz.martykan.forecastie.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1068)
	at java.lang.Float.parseFloat(Float.java:459)
	at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:464)
	at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:213)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6701)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2662)
	... 9 more
```

One more log from me.

**Comment by robinpaulson** [comment] 2019-04-18 23:20
Is this fixed with the latest release, 1.10.4?

**Comment by ChefKeeper** [comment] 2019-04-19 17:51
Hey, yes looks like it's fixed, haven't seen the crash since few days :smiley: 
Thanks ! :+1:

**Comment by mkulesh** [comment] 2019-04-21 09:10
I installed the release 1.10.4 two days ago and it looks like the problem is fixed - no more crashes for the last two days. Thank you for fixing this issue!

**Comment by robinpaulson** [comment] 2019-04-22 01:03
Excellent

**Closed** 2019-04-22 01:03 UTC
Labels: bug
