### ISSUE TITLE
Add other days of the week to the widget

### ISSUE THREAD

**Issue by pinportal** [martykan/forecastie#433] opened 2020-01-23 03:58 UTC
Currently the application widget shows only the weather data for today and for the user to be able to view the data for "tomorrow" and the following days, he needs to click and open the application. It would be more interesting to add this function to the application widget.

**Comment by pinportal** [comment] 2020-01-23 04:02
See the difference of the widget in relation to another application (above) and the forecastie widget (below)

https://i.imgur.com/JbHaOAc.jpg

**Comment by robinpaulson** [comment] 2020-01-23 08:19
We are interested in expanding the widget, but that will take time, we need to consider how we will do that. #426 has more info on the topic.

Also, closing as it's a duplicate of #34

**Closed by robinpaulson** 2020-01-23 08:19 UTC
