### ISSUE TITLE
Temperature not being reported correctly

### ISSUE THREAD

**Issue by brarcher** [martykan/forecastie#207] opened 2017-06-27 18:16 UTC
After updating this morning to v1.4 I noticed that the temperature being reported for my area is a bit hotter than usual:

![screenshot_20170627-074413](https://user-images.githubusercontent.com/5264535/27603018-bde42430-5b42-11e7-9c1f-cc3107c1f640.png)

As my area is not a wasteland today (the readout is over 200C), I assume the value is being reported incorrectly. Downgrading back to v1.2 finds the temperature being reported correctly again:

![screenshot_20170627-074537](https://user-images.githubusercontent.com/5264535/27603010-b4abaef6-5b42-11e7-8756-22e494aeb89d.png)

If there is a conversion being done between fahrenheit and celsius, the conversion may be incorrect.

**Comment by robinpaulson** [comment] 2017-06-28 04:06
Downgrading's not necessary, it works fine. You might need to confirm temperature units in the settings

Check issue #206

**Comment by brarcher** [comment] 2017-06-28 12:02
I do confirm that when upgrading to v1.4 again that the temperature setting was dropped, leaving the app in a state where it reported temperature value in kelvin but reported the temperature unit in Celsius. It seems there is a bug, namely that the temperature unit setting was dropped when upgrading from v1.2 -> v1.4. If this is the case, then the bug report in https://github.com/martykan/forecastie/issues/206 is not yet resolved and may result in other users who are upgrading (at least who uses the Celsius units) will be affected.

**Comment by robinpaulson** [comment] 2017-06-29 09:30
OK, point taken. I'm not sure what to do though, any suggestions?

**Comment by ildar** [comment] 2017-07-01 05:53
Set the temperature units during upgrade data on startup to that of the
previous version inherited, considering default value?

**Comment by robinpaulson** [comment] 2017-07-02 04:26
Closing again, as duplicate of #206

**Closed by robinpaulson** 2017-07-02 04:26 UTC
