### ISSUE TITLE
Version 1.4 broke the Clock Widget

### ISSUE THREAD

**Issue by Nutomic** [martykan/forecastie#208] opened 2017-06-29 09:25 UTC
After updating from 1.2 to 1.4, the 4x2 widget is completely broken (I didnt try 1.3 because that's not on F-Droid).

[Version 1.2](https://user-images.githubusercontent.com/1044450/27680849-256037d2-5cf8-11e7-8017-3b6020bd1d10.png)
[Version 1.4](https://user-images.githubusercontent.com/1044450/27680850-271d6bee-5cf8-11e7-9e28-360cf1a46434.png)

I guess you were doing this to add an alternative widget? In that case, please make a seperate widget for that, and restore the clock widget to its previous state.

**Comment by robinpaulson** [comment] 2017-06-29 09:29
I think there are two widgets now, did you try the other?

Also, v1.3 was broken; f-droid didn't build it.

**Comment by Nutomic** [comment] 2017-06-29 10:04
Here are both widgets from 1.4, none of them looks like the clock widget in 1.2.

[Version 1.4 Widgets](https://user-images.githubusercontent.com/1044450/27682498-b7bcbc86-5cfd-11e7-9d93-6bdaabd53dec.png)

**Comment by robinpaulson** [comment] 2017-06-29 10:12
Hmm, yes I see. I'll have to take a look at the changes that were introduced after v1.2. That might take a few days though. Unless you'd care to take a look and see what happened?

**Comment by Nutomic** [comment] 2017-06-30 03:33
Sorry but I don't really have the time. And I'm not familiar with the code either.

**Comment by robinpaulson** [comment] 2017-07-07 09:45
I think this is something @abika did in https://github.com/martykan/forecastie/commit/456fdc2a36901567d0d3f42b176b55f4da2336c0. Perhaps he has an idea how to fix it? I believe the rationale was to fit the same information into a smaller space.

**Comment by abika** [comment] 2017-07-07 19:30
See #184. I changed the clock widget for having a suitable layout for 4x1 and 4x2. 

The problem is that we actually need a widget layout with own space settings each for every possible screen resolution - Android can't handle this somehow (or I'm too stupid to figure it out).
And what I can say from the screenshot of the other bigger widget (I didn't touch) is that the cloud icon is not scaled to the available size. Could be depending on the Android version?

@Nutomic sorry, if you really want the old widget back, a third widget with the old layout must be created.
@robinpaulson how does it look for you? Is there at least somebody besides me who has a good looking widget?

**Comment by robinpaulson** [comment] 2017-07-07 22:01
As far as I'm concerned it works fine, but could do with some reordering, there are big blocks of empty space.

**Comment by robinpaulson** [comment] 2017-07-15 07:05
@abika In that case, I think something has gone wrong. It appears the widget has a lot of empty space; I'm not sure why, considering the screenshots you included with the PR. I don't think you're stupid, as you say it's probably an issue with screen res and how Android deals with that.

**Comment by robinpaulson** [comment] 2019-01-17 03:14
@abika and @Nutomic Checking in because it's been a while: does this bug still exist?

**Comment by Nutomic** [comment] 2019-01-17 11:37
Nope, its still broken. Or rather, it looks like the widget was changed to 4x1, so it looks completely different from the original widget in my first screenshot. Maybe that could be readded as a seperate widget?

**Comment by robinpaulson** [comment] 2019-10-17 10:51
We made some significant changes to the widgets recently; could you let us know what you think.

**Comment by igor-cali** [comment] 2019-11-06 22:05
I have included an additional 'Forecastie Classic' widget, taken out from release 1.2.
After some test and code cleanup, this could be merged and closed.


![Schermata del 2019-11-06 23-02-49](https://user-images.githubusercontent.com/12466054/68341954-d5a59500-00e9-11ea-8a80-7773d8298925.png)

**Closed** 2019-12-04 23:42 UTC
Labels: bug, help wanted, widget
