### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by emersion** [martykan/forecastie#157] opened 2016-10-13 12:43 UTC
Add support for alerts, which notify you when it's going to rain.

**Comment by sim6** [comment] 2017-01-28 22:16
Please add notifications also for low temperature.

**Comment by robinpaulson** [comment] 2017-06-08 10:06
Duplicate of #192 
Yes, I know this one was requested first, but 192 has more info/use cases listed so is a good start point.

**Closed by robinpaulson** 2017-06-08 10:06 UTC
Labels: duplicate
