### ISSUE TITLE
Weather maps "Wind" and "Temperature" encountered an error in landscape mode

### ISSUE THREAD

**Issue by ahyar92** [martykan/forecastie#283] opened 2018-05-19 20:06 UTC
#### Expected behavior
Supposedly, weather maps effects "Wind" and "Temperature" can be seen in landscape mode.

#### Actual behavior
When I go into the "Weather Map" feature and be in "Wind" weather. While in portrait mode, the wind effect works well, but when I change the rotation to landscape mode, suddenly weather map "Wind" does not work. And the same thing happens when viewing weather map "Temperature" in landscape mode.

#### How to reproduce
1. Install and open the app
2. Go to the "Weather Map" feature
3. Next open weather map "Wind" or "Temperature"
4. Next, change the rotation to landscape mode, then you will see weather map "Wind" or "Temperature" not working.

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 

#### Recording Of The Bug
https://www.youtube.com/watch?v=9UJlPoeaRio

**Comment by robinpaulson** [comment] 2019-01-17 03:04
@ahyar92 Is the bug fixed with the latest release, v1.6.4?

**Comment by robinpaulson** [comment] 2019-01-17 03:06
This is a duplicate of #275. Closing

**Closed** 2019-01-17 03:06 UTC
Labels: bug
