### ISSUE TITLE
Dark Sky

### ISSUE THREAD

**Issue by moriel5** [martykan/forecastie#179] opened 2017-01-29 09:02 UTC
Could you please add Dark Sky as a weather provider?
Unfortunately, OpenWeatherMaps refuses to recognize my location, and my efforts to contribute were met with complete denial, and ever since I had tried to help get locations in my area into OpenWeatherMap, the situation had only worsened (it used to find my location correctly at rare intervals, now it never does).
Although it is discouraged, you could allow the user to use his/her API token (I have one which I use with the OpenWeather extension for GNOME).

**Comment by kompowiec** [comment] 2017-03-28 08:45
https://github.com/Benjamin3992/OpenWeatherDuino
arduino it protip

**Comment by robinpaulson** [comment] 2017-06-08 10:19
duplicate of #126

**Closed by robinpaulson** 2017-06-08 10:19 UTC
