### ISSUE TITLE
forecastie crashed on start

### ISSUE THREAD

**Issue by kompowiec** [martykan/forecastie#112] opened 2016-08-02 07:36 UTC
Hi. When in phone don't have internet not at all, it run application cause crash.

If app download in data early on 3 days it nice to have if these daty later offline

**Comment by martykan** [comment] 2016-08-04 18:28
Works for me. Does it happen often?

**Comment by kompowiec** [comment] 2016-08-05 16:35
Somethimes. Now i see that is it strange - when first installed application (fdroid) it crash was always and just format phone helped. Afther nothing and serveral times when added issue (when i was on bumfuck). Now i can't replace without reason (because now write that don't have internet and I didn't update).

I think that so issue closed.

**Comment by Nutomic** [comment] 2016-08-13 20:12
I'm getting the same issue with the latest F-Droid version. Can try to get a log soon if that helps.

**Comment by martykan** [comment] 2016-08-13 21:05
Any logs help, but git master would be ideal.

**Comment by martykan** [comment] 2016-08-14 19:35
So I will close this if @kompowiec can't replicate this again.

**Comment by Nutomic** [comment] 2016-08-14 21:47
I also tried to reproduce this today, but couldn't do it.

**Comment by martykan** [comment] 2016-08-15 08:49
Okay, so I will keep this open. If this happens to anyone again, please try to get a log of the crash.

**Comment by kompowiec** [comment] 2016-08-21 12:48
i installed syslog and still wait on appear crash.

**Comment by martykan** [comment] 2016-08-21 13:13
OK, great.

**Comment by kompowiec** [comment] 2016-08-26 16:55
I'm very sorry but someone steal my phone with android and must buy new... unlikely to deliver within a reasonable time (if ever succeed).

**Comment by martykan** [comment] 2016-08-26 17:57
Oh, that sucks. There's a chance you can find it, thieves are usually not very smart and keep accounts logged on.

**Comment by kompowiec** [comment] 2017-01-09 17:25
actual i have android 6.0 and can't replace the bug - i think that can closed.

**Comment by Nutomic** [comment] 2017-01-09 19:35
No this crash seems to be fixed for me.

**Comment by robinpaulson** [comment] 2017-06-08 10:15
Closing, it appears gone for now.

**Closed by robinpaulson** 2017-06-08 10:15 UTC
