### ISSUE TITLE
Feature: allow picking City when multiple results available w/o GPS

### ISSUE THREAD

**Issue by troyengel** [martykan/forecastie#259] opened 2018-01-04 01:46 UTC
For some cities there are multiple results when searching by text name, like this example:

* https://openweathermap.org/find?q=san+antonio%2C+us

Forecastie appears to just pick the first one in the list, we should present the user a popup to choose which one. This is difficult visually, because the OWM data doesn't appear to list Locality (State, e.g.), they simply rely on Geo coordinates that are painful to "just know" for any average user. One of these example results is not in USA of course, so we have a larger problem as the result list crosses national boundaries.

Not sure how to visually represent in the app this other than a popup listing the choices with the geo coordinates, and expect the user to go look them up for themselves? Maybe if the popup linked those coordinates to launch Google Maps? (I can take them as-is from OWM and maps.google.com finds them no problem) Something is better than just randomly picking the first result...

Note: this is with Location / GPS disabled, just using the search eyeglass method
  
(edit: sorry my example didn't make sense there when I said "outside the US" - if you search 'San Antonio' that happens, drop the US. My mistake as I was writing this.)

**Comment by robinpaulson** [comment] 2018-11-25 22:48
Yep, again decent reverse-geocoding will fix this.

**Comment by andrewmattie** [comment] 2019-01-27 05:02
Would something like this work? https://imgur.com/a/qgeVeyO

**Comment by troyengel** [comment] 2019-01-27 13:40
I think that looks really cool! I would suggest adding the country as well - using the same example as above without the country ( https://openweathermap.org/find?q=san+antonio ) we get 5 different countries which appear in the results, seems like a good move to include? neat. :)

**Comment by andrewmattie** [comment] 2019-01-28 20:38
I'm glad you like it! Appending the country to the city is something I had meant to do so thanks for the reminder. I've gone a head and made the change. It makes it a lot easier to identify the city at a glance. https://imgur.com/a/GvivOgb

**Comment by robinpaulson** [comment] 2019-02-01 09:14
This is really excellent, @andrewmattie . If you want to make a PR, I will be glad to add this to the app. Including the country would be good too.

**Comment by robinpaulson** [comment] 2019-02-01 21:15
Duplicate of #183

**Closed by robinpaulson** 2019-02-01 21:15 UTC
Labels: bug

**Comment by atpage** [comment] 2019-04-08 16:13
> Would something like this work? https://imgur.com/a/qgeVeyO

In 1.10.3, the maps in the Locations selector all come up blank for me.  Any suggestions, or should I submit a separate bug?

**Comment by robinpaulson** [comment] 2019-04-12 02:50
@atpage Could this be an internet connectivity problem? If you still can't get it to work, then yes, please open a new issue.
