### ISSUE TITLE
Suggestion: weekly widget

### ISSUE THREAD

**Issue by toxpal** [martykan/forecastie#567] opened 2020-12-16 10:42 UTC
After lots of search for open-source weather app, I decided to stick with Forecastie and really like it. The only thing I miss - weekly widget (just like 99% of weather apps have) that displays forecast for several days (usually most widgets display today's data + data for upcoming 4 days, so 5 days total).

Is there any chance to have a weekly widget that displays forecast for today + a few more days?

**Comment by robinpaulson** [comment] 2020-12-16 13:11
Yep, this was requested all the way back in mid-2016!

Unfortunately nobody has got round to it yet. I've done a bit of poking around in the existing widgets recently and think I have a good idea of how they work. I'll see what I can come up with.

**Comment by robinpaulson** [comment] 2020-12-16 13:12
LCosing, dupe of #34

**Closed** 2020-12-16 13:11 UTC
Labels: duplicate
