### ISSUE TITLE
Unit is incorrect on install

### ISSUE THREAD

**Issue by gappleto97** [martykan/forecastie#213] opened 2017-07-03 16:34 UTC
Just grabbed the F-Droid version, and by default it showed Kelvin, but labelled it as Celsius.

**Comment by ramack** [comment] 2017-07-03 20:33
isn't this a duplicate of #206 ?

**Comment by gappleto97** [comment] 2017-07-03 20:41
Appears to be. I guess I should file an issue in FastHub for the search function now. I keep forgetting it's broken.

**Comment by robinpaulson** [comment] 2017-07-04 04:12
Yep, it is a duplicate. Please search before posting.

**Closed** 2017-07-04 04:12 UTC
