### ISSUE TITLE
Too much requests, please try again.

### ISSUE THREAD

**Issue by stemy2** [martykan/forecastie#239] opened 2017-08-13 13:10 UTC
Hello,

I can't obtain any weather info from the app, just an error message when i try to update: Too much requests, please try again.

**Comment by Lemmiwinks** [comment] 2017-08-13 13:22
Having the same problem!

**Comment by robinpaulson** [comment] 2017-08-14 00:50
#182 #236 #238

Closing

**Closed** 2017-08-14 00:50 UTC

**Comment by stemy2** [comment] 2017-08-14 06:52
Why did you closed the subject without any explanation ? Will it be an upgrade or you will do nothing ?

**Comment by ildar** [comment] 2017-08-14 07:17
He gave enough references to understand:
1. The issue is known.
2. The issue is discussed elsewhere.
3. This issue has no useful information that's unavailable in other issues.

Also my 5 cents: please look around in other issues before opening another.
