### ISSUE TITLE
Crash on first start

### ISSUE THREAD

**Issue by fizzgig242** [martykan/forecastie#336] opened 2019-03-19 11:48 UTC
Hello there,

when I start the app for the first time it crashes every time.

After that I am able to restart it and it works as intended.

I am using the app on a Redmi Note 4 with LineageOS 15.1.

**Comment by robinpaulson** [comment] 2019-03-20 04:33
By "the first time", do you mean the first time after you boot your phone, or the first time after you install an update to forecastie?

**Comment by fizzgig242** [comment] 2019-03-21 19:39
I mean it crashes everytime when I start it. After that I restart the app and it works like a charm.

**Comment by robinpaulson** [comment] 2019-03-22 23:25
I realise now that I've been getting the same bug for a while; not every start, but probably more than not. I think my mind had blocked it out, accepted it without thinking.

**Comment by marcoM32** [comment] 2019-03-26 18:25
I have the same bug and in my case this error appear on logcat console:

FATAL EXCEPTION: main
Process: cz.martykan.forecastie, PID: 16181
java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.martykan.forecastie/cz.martykan.forecastie.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
	at android.app.ActivityThread.access$900(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5451)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at java.lang.StringToReal.parseFloat(StringToReal.java:304)
	at java.lang.Float.parseFloat(Float.java:306)
	at cz.martykan.forecastie.activities.MainActivity.updateTodayWeatherUI(MainActivity.java:464)
	at cz.martykan.forecastie.activities.MainActivity.onStart(MainActivity.java:213)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6340)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
	... 9 more

**Comment by robinpaulson** [comment] 2019-03-27 01:24
Cheers @marcoM32 , this helps.

**Comment by robinpaulson** [comment] 2019-04-18 23:19
Fixed with the latest release

**Closed** 2019-04-18 23:20 UTC
Labels: bug
