### ISSUE TITLE
Detect Location pulls up the wrong city with the same name

### ISSUE THREAD

**Issue by bedaro** [martykan/forecastie#266] opened 2018-01-16 17:08 UTC
Hi,

In version 1.6.1, if I use "Detect Location" from Northeast Seattle, WA (zip 98115) right across the lake from Kirkland, WA, the app detects my location as Kirkland probably because of the cell tower. The issue, possibly related to #259, is that the weather being shown after my location is detected as "Kirkland, US" is clearly not what's happening in Kirkland, WA (yesterday it said it was snowing, right now it says 21 F when it's at least 20 degrees warmer). This is probably the weather for a different US city also named Kirkland--maybe the IL one?

While the proposed resolution for issue #259 is to show a pop-up when results are ambiguous, if this problem shares the same root cause (retrieving weather info based on a city name search), the solution here should be to pick the closest matching city using the geo coords. From a quick skim of the OpenWeather API, though, I'm not sure I understand why city name would be used at all for a "Detect Location" lookup; why not query based on lat and lon coordinates?

I made some Android apps a long time ago so if I get the time this week or next I may investigate how to fix this myself, that is if it's not being addressed already.

**Comment by chreekat** [comment] 2018-03-28 01:45
Came to report the same thing. Brooklyn, NY

**Comment by chreekat** [comment] 2018-03-28 01:48
You can see what city it thinks you're in by going to the weather map, btw.

**Comment by h-theLetter** [comment] 2018-04-22 14:11
Same issue here. It seems to return the first matching city with the same name from OpenWeatherMap.

**Comment by robinpaulson** [comment] 2018-11-25 22:44
> I'm not sure I understand why city name would be used at all for a "Detect Location" lookup; why not 
> query based on lat and lon coordinates?

Ill take a guess: the author is based in Europe, a region which has less problematic naming than the US. There is likely only one "Cologne" or "Paris" or "Warsaw" in Europe, due to huge variations in dialect and language, meaning twns with the apparent same origin tend not to have the same spelling or even character set. Names in the US tend to be used over and over, always in English (although sometimes transliterated from German, Swedish, Spanish, etc.). Also, OWM provides the country, not the state/region, again favouring finding the correct place in Europe compared to the US. Given we now understand the way owm provides results, we can act to fix this. As to the second part, I assume owm does some reverse-geocoding if required, turning a name into a lat,lon pair. We could do this ourselves, using nominatin (http://nominatim.org/) or similar.

**Comment by robinpaulson** [comment] 2018-11-25 22:45
Help requested finding out how nominatin works in android apps. There is probably a library.

**Comment by andrewmattie** [comment] 2019-01-24 05:31
@robinpaulson Currently the app is getting the correct city through the user's lat long but then just does a search by city name leading to the inaccuracy. I believe this could be resolved by using the cityId for the query instead of city name.

**Comment by andrewmattie** [comment] 2019-01-25 01:34
Yeah, it is. I'm currently looking through the code now to see the best way to implement this and if it will fix the bug.

**Comment by andrewmattie** [comment] 2019-01-27 04:41
Ok, I've got the cityId changes implemented and it looks like everything works as it should and the bug is fixed. I'm just going to wait for the other PRs to be merged before creating a new one.

**Comment by robinpaulson** [comment] 2019-02-01 09:15
Please do! @andrewmattie

**Comment by robinpaulson** [comment] 2019-02-01 21:14
Closing, as this appears to be a dupe of #183

**Closed by robinpaulson** 2019-02-01 21:14 UTC
Labels: bug, help wanted

**Comment by Lee-Carre** [comment] 2022-03-15 03:33
For context, I recently learned (via a mail exchange with staff) that OWM uses [GeoNames](//www.geonames.org/) ([map](//www.geonames.org/v3/)) for locations.

So, it would seem sensible to first ensure that the desired cities are correct & unambiguous in the GeoNames data.
