### ISSUE TITLE
Get data from AEMET OpenData API for Spain

### ISSUE THREAD

**Issue by logos88** [martykan/forecastie#589] opened 2021-05-15 11:53 UTC
From my experience OpenWeatherMap data for Spain is not very accurate.

It would be great if you could choose to use data from AEMET (Spanish Meteorological Agency) instead of OpenWeatherMap in the configuration.

AEMET has an open API with different open data which offers freely:

https://www.aemet.es/en/datos_abiertos/AEMET_OpenData

https://opendata.aemet.es

**Comment by robinpaulson** [comment] 2021-05-15 23:20
Yes, there have been a few comments that OWM has poor forecasts in some areas, with corresponding requests to use other data providers. It's certainly a valid ask, the question is the complexity; it's no small thing to do. If someone has the time to do all or even a large part of it, of course it'll be accepted into the code base. For now though, that looks unlikely.

**Comment by robinpaulson** [comment] 2021-12-06 04:29
Closing, as it's a dupe of #126

**Closed** 2021-12-06 04:30 UTC
Labels: enhancement, complexity: HIGH, urgency: LOW

**Comment by Lee-Carre** [comment] 2021-12-26 04:20
Would it not be better to ask OWM to use the Spanish data itself? Everyone benefits, then.

**Comment by robinpaulson** [comment] 2021-12-26 23:45
@logos88 See another issue related to this: #126
