### ISSUE TITLE
 Comprehensive FAQs for this Project

### ISSUE THREAD

**Issue by autofreak** [martykan/forecastie#353] opened 2019-05-29 22:31 UTC
Hello, I would love to create FAQs for this project, having used the app for weeks, I think it is about time we include it.

Nothing feels better than open source:)

**Comment by robinpaulson** [comment] 2019-08-11 01:14
OK, great. Do it if you wish.

**Comment by robinpaulson** [comment] 2019-08-11 01:38
Closing, duplicate of #281

**Closed by robinpaulson** 2019-08-11 01:38 UTC
Labels: enhancement
