### ISSUE TITLE
[Bug] Error parsing JSON

### ISSUE THREAD

**Issue by Primokorn** [martykan/forecastie#35] opened 2016-01-22 16:10 UTC
Hi

I'm running a custom CM13 based rom (Temasek) and I have the attached error at launch.

[logcat_and_device_info.zip](https://github.com/martykan/forecastie/files/101064/logcat_and_device_info.zip)

Thank you.

**Comment by martykan** [comment] 2016-01-22 16:12
The problem is because of the API key. I don't know what exactly happened, but I fixed it a few minutes ago in v0.8. It will take a few hours until it gets fixed on F-Droid

**Comment by andreasspeck** [comment] 2016-01-24 15:36
0.8 is not yet in F-Droid.

The limitations that come with the free API key are pretty low (60 calls per minute, or 50,000 calls per day). I think as Forecastie is clearly the best app out there that makes use of OpenWeatherMap, it might already be too popular for that limit.
It would be best for the app to have a default API key but make it configurable, and advise people on how to create their own account and enter their own API key. That way you would avoid reaching the limit (an individual person is unlikely to reach the limit - but thousands of users using the same API key might get there...).

**Comment by johannesgunnar** [comment] 2016-01-25 16:44
Just commenting here to note that I am running into the same problem on CM 12.1-20151117, with Forecastie 0.7 gotten from F-Droid. (no sign of 0.8 so far on f-droid)

**Comment by Primokorn** [comment] 2016-01-26 10:09
Thanks martykan. Update requested to F-Droid team.

**Comment by martykan** [comment] 2016-01-26 10:17
F-Droid already built the new version, we just need to wait for the repo update.
https://f-droid.org/wiki/page/cz.martykan.forecastie/lastbuild_8

**Comment by Primokorn** [comment] 2016-01-26 12:25
Update available :)

**Closed** 2016-01-26 12:46 UTC
