### ISSUE TITLE
Option to make widget transparent

### ISSUE THREAD

**Issue by nachoparker** [martykan/forecastie#217] opened 2017-07-06 05:44 UTC
It would be great if the widget could be transparent.

As I have it now it is blue without the option to change it. I am guessing most users will not be using a blue theme/background. ;)

Great job otherwise!

Thanks

**Comment by robinpaulson** [comment] 2017-07-07 04:56
Hi yeah, this is a dupe of #133

Please read existing issues before posting. Closing

**Closed** 2017-07-07 04:57 UTC

**Comment by nachoparker** [comment] 2017-07-07 06:06
sorry, I did skim through all the issues, but didn't see it!

thanks again for the project
