### ISSUE TITLE
Temperature as integer does not affect all temps

### ISSUE THREAD

**Issue by jabranham** [martykan/forecastie#181] opened 2017-03-01 09:12 UTC
Thanks for the great app. Related to #98. 

The "show temperature as integer" setting does not seem to affect the forecasted temperatures (e.g. those below the today/tomorrow/later buttons).

**Comment by artem-p** [comment] 2017-03-11 13:18
For me, it works as expected.

**Comment by robinpaulson** [comment] 2017-04-20 06:45
As far as I can tell, it also isn't reflected in the graphs, they only appear to show integer temperatures.

**Comment by robinpaulson** [comment] 2017-06-09 13:40
I can't reproduce the bug @jabranham reports either. I fixed the part I added, in #200 
closing for now, please reopen if you still get the bug

**Closed by robinpaulson** 2017-06-09 13:40 UTC
Labels: bug
