### ISSUE TITLE
It's not detecting location

### ISSUE THREAD

**Issue by princev558** [martykan/forecastie#323] opened 2019-02-16 09:27 UTC
Detect Location is not working

**Comment by robinpaulson** [comment] 2019-02-17 06:41
Perhaps a *tiny* bit more detail?

**Comment by zeugmatis** [comment] 2019-04-05 22:09
Looks like this might be a dupe of #325.

**Comment by robinpaulson** [comment] 2019-04-12 02:47
@zeugmatis Possibly, or it could be an error elsewhere in the location stack; poor GPS reception, microG bug (it is very crashy on my device), etc.

**Comment by robinpaulson** [comment] 2019-04-21 02:05
I'm going to assume this is indeed a dupe and close, please add more comments if required

**Closed by robinpaulson** 2019-04-21 02:05 UTC
