### ISSUE TITLE
Feature request - Temperature in status bar

### ISSUE THREAD

**Issue by chihuahua45** [martykan/forecastie#481] opened 2020-06-02 05:02 UTC
Allow to show temperature in status bar as an integer

**Comment by robinpaulson** [comment] 2020-06-05 06:07
Yes. I think we've talked about this before, but I can't find it now. Perhaps a little more info than temperature - wind speed, weather icon, rain, etc.

**Comment by chihuahua45** [comment] 2020-06-06 05:16
> Yes. I think we've talked about this before, but I can't find it now. Perhaps a little more info than temperature - wind speed, weather icon, rain, etc.

Oh thats great... I thought i was the only one who hated widgets.

Btw, didn't really know an app could place so many icons on the status bar. Ideally, i'd like to see both temperature and weather icon

**Comment by robinpaulson** [comment] 2020-06-07 22:39
To be clear: while this is a good idea, it will only be implemented if somebody has the time energy and skills to do so.

**Comment by robinpaulson** [comment] 2020-07-08 16:45
Found it! #19. I'll close this as it's a dupe of that.

**Comment by robinpaulson** [comment] 2020-10-19 00:23
Reopened as per request from @fAntel in #551

**Comment by robinpaulson** [comment] 2021-12-08 06:46
This has been added, as of #605

**Closed by robinpaulson** 2021-12-08 06:46 UTC
Labels: enhancement, complexity: MEDIUM, urgency: LOW
